services:
  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    environment:
      NEXTCLOUD_DATADIR: /var/www/html/data
    volumes:
      - nextcloud_data1:/var/www/html
volumes:
  nextcloud_data1:
